---
- hosts: all

  vars:
    services_user: vagrant
    services_group: vagrant
    vimconfig_repo: git@github.com:macseem/vimconfig.git
    home_dir: /home/vagrant
    vimconfig_dir: /vimconfig
    uniwatch_repo: git@github.com:macseem/uniwatch.git
    uniwatch_dir: /var/www/uniwatch
    composer_path: /usr/local/bin
    composer: /usr/local/bin/composer
    ansible_dir: /vagrant/ansible

    db_host: localhost
    db_user: root
    db_password: ""
    db_name: uniwatch
    db_init_file: db/init.sql

  tasks:

  - name: Apt-get update
    sudo: yes
    apt: update_cache=yes

  - name: Setup git
    sudo: yes
    apt: name=git state=present

#Setup nginx, php, curl, mysql
  - name: Setup nginx
    sudo: yes
    apt: name=nginx state=present
  - name: Load nginx.conf
    sudo: yes
    template: src=nginx/nginx.conf
              dest=/etc/nginx/nginx.conf

  - name: Setup php5-fpm
    sudo: yes
    apt: name=php5-fpm state=present
  - name: Setup php5-cli
    sudo: yes
    apt: name=php5-cli state=present
  - name: Load php5/cli.ini
    sudo: yes
    template: src=php/cli.ini
              dest=/etc/php5/cli/php.ini
  - name: Load php5/fpm.ini
    sudo: yes
    template: src=php/fpm.ini
              dest=/etc/php5/fpm/php.ini
  - name: Load php5/php-fpm.ini
    sudo: yes
    template: src=php/php-fpm.conf
              dest=/etc/php5/fpm/php-fpm.conf
  - name: Load php5/www.conf
    sudo: yes
    template: src=php/www.conf
              dest=/etc/php5/fpm/pool.d/www.conf

  - name: Setup php-pear
    sudo: yes
    apt: name=php-pear state=present

  - name: Setup curl
    sudo: yes
    apt: name=curl state=present
  - name: Setup php5-curl
    sudo: yes
    apt: name=php5-curl state=present

  - name: Setup mysql-server
    sudo: yes
    apt: name=mysql-server state=present
  - name: Setup mysql-client
    sudo: yes
    apt: name=mysql-client state=present
  - name: setup php5-mysql
    sudo: yes
    apt: name=php5-mysql state=present
#End Setup nginx, php, curl, mysql

#Setup vim
  - name: Setup vim
    sudo: yes
    apt: name=vim state=present
  - name: Add github to ssh_known_hosts
    shell: ssh-keyscan -H -t dsa github.com >> ~/.ssh/known_hosts 2>&1
  - name: Clone vimconfig
    git: repo={{ vimconfig_repo }}
         dest={{ home_dir }}{{ vimconfig_dir }}
  - name: Install vimconfig       
    shell: chdir={{ home_dir }}{{vimconfig_dir}} /bin/bash install.sh
#End Setup vim
  - name: Remove apache if exists
    sudo: yes
    apt: name=apache2 state=absent

#Install composer
  - name: Install composer
    sudo: yes
    shell: curl -s https://getcomposer.org/installer | php
  - name: Move composer to /usr/local/bin
    sudo: yes
    shell: sudo mv composer.phar {{ composer_path }}/composer
  - name: Make composer file permissions
    sudo: yes
    file: path={{ composer_path }} mode=0755
  - name: Do composer self-update
    sudo: yes
    shell: "{{ composer }} self-update"
#End Install composer



  - name: Install phpmyadmin
    sudo: yes
    apt: name=phpmyadmin state=present
  - name: Make simlink to phpmyadmin
    sudo: yes
    shell: chdir=/usr/share/nginx/html ln -s /usr/share/phpmyadmin
    #template: src=nginx/sites-enabled/phpmyadmin
    #          dest=/etc/nginx/sites-enabled/phpmyadmin

#Install uniwatch
  - name: Clone project
    git: repo={{ uniwatch_repo }}
         dest={{ uniwatch_dir }}
  - name: Do composer -vvv install
    shell: "chdir={{ uniwatch_dir }} {{ composer }} -vvv install"
  - name: Setup sites-enabled/uniwatch
    sudo: yes
    template: src=nginx/sites-enabled/uniwatch
              dest=/etc/nginx/sites-enabled/uniwatch
  - name: Init Db
    shell: mysql -h{{ db_host }} -u{{ db_user }} < {{ ansible_dir }}/{{ db_init_file }}
  - name: Make migrations
    shell: chdir={{ uniwatch_dir }} php ./yii migrate/up --interactive=0

#  - name: Init crontab
#    ...
#End Install uniwatch

#Reload services
  - name: Reload nginx
    sudo: yes
    service: name=nginx state=reloaded
  - name: Reload php5-fpm
    sudo: yes
    service: name=php5-fpm state=reloaded



